[package]
name = "zlmediakit-rtmp"
description = "RTMP protocol implementation"
version.workspace = true
edition.workspace = true

[dependencies]
zlmediakit-core = { path = "../core" }
zlmediakit-codec = { path = "../codec" }
zlmediakit-mp4 = { path = "../mp4" }
tokio.workspace = true
bytes.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
async-trait.workspace = true
futures.workspace = true
hmac.workspace = true
sha2.workspace = true
rand.workspace = true
rustls.workspace = true
tokio-rustls.workspace = true
rustls-pki-types.workspace = true

[dev-dependencies]
rcgen.workspace = true
tempfile = "3"
