[package]
name = "zlmediakit-hls"
description = "HLS muxer/demuxer"
version.workspace = true
edition.workspace = true

[dependencies]
zlmediakit-core = { path = "../core" }
zlmediakit-codec = { path = "../codec" }
zlmediakit-mp4 = { path = "../mp4" }
tokio.workspace = true
bytes.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
async-trait.workspace = true
chrono.workspace = true
