[package]
name = "zlmediakit-mp4"
description = "MP4 muxer/demuxer"
version.workspace = true
edition.workspace = true

[dependencies]
zlmediakit-core = { path = "../core" }
zlmediakit-codec = { path = "../codec" }
bytes.workspace = true
anyhow.workspace = true
tracing.workspace = true
tokio.workspace = true
chrono.workspace = true
